### ISSUE TITLE
Support Cluster API provider IPAM In Cluster through Rancher Manager

### ISSUE THREAD

**Issue by jisnardo** [rancher/turtles#692]
**Describe the solution you'd like:**

Support Cluster API provider IPAM **In Cluster** through Rancher Manager.

https://cluster-api.sigs.k8s.io/reference/providers#ip-address-management-ipam

https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster

**Why do you want this feature:**

Manage pools of IP addresses using Kubernetes resources as a simple replacement for DHCP.

**Anything else you would like to add:**

Extend to Hosted Kubernetes providers (vSphere/EKS/AKS/GKE)

**Comment by jisnardo** [comment]
With rancher-turtles v0.10.0, cluster-api core provider v1.4.6 and ipam provider v0.1.0 added as custom add-on through rancher manager, the controller does not start.

k logs -f capi-ipam-in-cluster-controller-manager-b88444db8-c9xdf

`E0902 13:57:35.349342       1 main.go:109] "failed to setup indexes" err="failed to get API group resources: unable to retrieve the complete list of server APIs: ipam.cluster.x-k8s.io/v1beta1: the server could not find the requested resource" logger="setup"`

If we deploy capi v1.8.1 + rke2 providers v0.6.1 without rancher / rancher turtles it works as expected.

**Comment by Danil-Grigorev** [comment]
@jisnardo I suspect you would need to perform upgrade to rancher 2.9 and then turtles to version v0.11+. This should update CAPI manifests version to 1.7.3, (check `CAPIProvider` status) which has `v1beta1` IPAM CRDs in-tree and will install them in cluster, which would render provider functional.

It might happen that the upgrade will not happen automatically, this should be fixed in the next patch release, but you can always specify `spec.version` to `v1.7.3` manually.

Rancher does not have support for IPAM providers in embedded CAPI scenario, which we advise to have disabled: https://turtles.docs.rancher.com/getting-started/install-rancher-turtles/using_rancher_dashboard

**Comment by jisnardo** [comment]
Hi @Danil-Grigorev, after upgrading we where able to add ipam in-cluster as custom provider type add-on. Thank you.

**Comment by furkatgofurov7** [comment]
@jisnardo thanks for confirming. Can this issue be closed now?

**Comment by jisnardo** [comment]
Yes @Danil-Grigorev, we are able to continue. Greetings.
